### ISSUE TITLE
Peer to peer code review

### ISSUE THREAD

**Issue by Strangeal** [adel-gu/Leaderboard#7]
### Peer-to-peer code review

- Correct Gitflow  ✅🥇
- Implemented Fetch and add for the Api ✅🥇
- Used proper Git flow ✅🥇
- Implemented The requirements ✅🥇

### Required Changes ♻️
- Please add an `overflow: scroll`, and` max-height to your recent score container so it stays on the page so you have keep scrolling through your scores without having to move away from the same page.
- Please add a `setTimeout()` to your **success message** so it disappears after a few seconds after submitting your form I think you can make also add a message for your refresh button and also a message to display when you submit an empty form.

**Comment by adel-gu** [comment]
Hi @Strangeal, 👋

Thank you for your catch👏👏👏.
Your suggestions were constructive and insightful, and because of that my project right now is just stunning   ✨
